### ISSUE TITLE
Generator fails when a 412 is returned

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#114]
This may actually be something that IPS does correctly and NSS does incorrectly. Nonetheless, because the generator was built for NSS, it fails.

To reproduce:

Log into https://develop.generator.inrupt.com and navigate to the profile page (with the dev tools open).

Upon making a request to get the user's card, the request will succeed once. This will return an e-tag header for the resource `ETag | "kRnn6U5l4/1Y/E1hKllJuA=="` (Note that NSS does not return an ETag header)

![image](https://user-images.githubusercontent.com/5464743/61818215-61870000-ae1e-11e9-8b35-a2e93e428ddd.png)

Upon making a second request for the resource, the browser automatically includes the If-None-Match header `If-None-Match | "kRnn6U5l4/1Y/E1hKllJuA=="`. The server then returns an error `412 Precondition Failed` which trips up the generator.

Based on what I know about the [If-None-Match header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match), this is the correct behaviour, though perhaps it should return a `304 Not Modified`

**Comment by michielbdejong** [comment]
Interesting! Yes, I think 412 is correct here, but if it's the browser inserting the If-None-Match header, then it should also be the browser who handles the 412 and gives the cached body back instead, with a 200.

@RubenVerborgh what do you think?

**Comment by RubenVerborgh** [comment]
This behavior is incorrect, MUST be 304:

>  the origin server MUST respond
   with either a) the 304 (Not Modified) status code if the request
   method is GET or HEAD or b) the 412 (Precondition Failed) status code
   for all other request methods.

—https://tools.ietf.org/html/rfc7232#section-3.2


But are we generating this status code ourselves, or a framework we’re using? Should be the latter.

**Comment by michielbdejong** [comment]
Thanks! Ah, that's actually also what @jaxoncreed's link says. Will change it from 412 to 304 in case of GET/HEAD.

**Comment by RubenVerborgh** [comment]
👍 IETF is the authoritative source for such matters (and they use MUST/SHOULD normative language)

How come the status code decision is up to us? I would expect a framework above to handle this for us? In any case, the knowledge of “x was not modified” and “not modified means 304 on GET/HEAD should likely be in different places.

**Comment by michielbdejong** [comment]
"x was not modified" is in https://github.com/inrupt/wac-ldp/blob/master/src/lib/operationHandlers/getResourceDataAndCheckETag.ts#L17
"not modified means 304" is in https://github.com/inrupt/wac-ldp/blob/master/src/lib/api/http/HttpResponder.ts#L71
"on GET/HEAD" wasn't there until now, but I'm adding WacLdpTask.isReadOperation to check it and then updating getResourceDataAndCheckETag.ts to respond differently in each of those cases.

I'm not aware of any framework that would be really helpful here, are you referring to middleware like koa? How would you tell koa to deal with this?
I found https://github.com/koajs/koa/blob/master/docs/api/request.md#requestfresh but that's for when making an outgoing request, not for when serving a resource.

**Comment by michielbdejong** [comment]
Fixed in the dev branch

**Comment by jaxoncreed** [comment]
Tested. confirmed to work

**Comment by RubenVerborgh** [comment]
> "x was not modified" is in [/src/lib/operationHandlers/getResourceDataAndCheckETag.ts@`master`#L17](https://github.com/inrupt/wac-ldp/blob/master/src/lib/operationHandlers/getResourceDataAndCheckETag.ts#L17) [](/inrupt/wac-ldp/blob/HEAD@{2019-07-26T12:24:06Z}/src/lib/operationHandlers/getResourceDataAndCheckETag.ts#L17)

Mmm, seems like that knowledge is now conflated in https://github.com/inrupt/wac-ldp/commit/c51a26cf214b49c8026832178b17b4900b806a76#diff-bf1bfa0c2a1d78edd9249ef7665b7e8eR9, since the thing checking "x was not modified" is now also responsible for knowing that "not modified means 304 not modified on read methods, 412 on others". One would expect separate etag validation logic and response generation logic for separation of concerns. I.e., when doing black-box unit testing now, one would have to test 4 x 3 + 1 = 13 conditions (4 error conditions for GET/HEAD/other, plus one regular case), as opposed to 4 + 1 + 3 = 8 cases.

> I'm not aware of any framework that would be really helpful here, are you referring to middleware like koa?

Indeed; though you're likely right, such frameworks will only handle the etag business for static resources they serve themselves. The `getResourceDataAndCheckETag` is a good mechanism for handling this in general, although am slightly concerned by https://github.com/inrupt/wac-ldp/blob/ac5a205088f6018f451049b0f79537edbcac1b9f/src/lib/operationHandlers/getResourceDataAndCheckETag.ts#L7 where it has knowledge about `getResourceData` and the URL (Demeter violation?); I would expect `resourceData` to be passed in. But I assume it is cached, i.e., `getResourceData` is not an expensive call when invoked repeatedly?

In any case, this issue is a good reminder that RFC7232 needs to be referred to explicitly from the spec; will follow up on that.
