### ISSUE TITLE
Explain why the architecture is not representation-oriented

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#138]
In https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-1-0.pdf, a case is made for what we could call a representation-oriented code architecture: resources are manipulated through representations, and the objects and references that are passed around between modules, also refer to representations rather than to resources.

While I think this is a clever proposal, I don't think it would work very well in practice. What we're trying to do with the current architecture is to separate unrelated concerns into different modules, and to use the principles of visibility and simplicity: each bit of code structure relates to a different part of the functionality that's implemented, and tries to break up a complex task into chunks with less context.

Specifically, there are rougly three types of requests the server can fulfill: 
* stream a resource from persistence to network (possibly do translation of it on the way)
* write data from network to persistence (again, possibly do translation of it on the way)
* RDF-aware operations on data, which mainly go into two categories:
  * requests to alter the data for which the server needs to "understand" the data as RDF
    * mainly sparql-update PATCH in the current spec
  * cases where the server's own functions rely on the RDF meaning of data stored in the pods
    * mainly the ACL system in the current spec

It deserves note that this last point is quite special, and it creates a bit of a mixing of layers, although it's also quite common in other servers, such as unix using special file references for things as `stdin`, or SQL using special tables to keep track of permissions. The system stores such things in a place that it knows always exists: itself. :)

But this is not in itself a reason to make all internals of the server more RDF-aware, just like when you build an email server, you probably don't use SMTP as a way to communicate between code modules. :) So the RDF-awareness is in two components:
* the `StoreManager` which stores `Quad`s in memory, executes sparql-update queries on them, and if necessary performs translations between RDF serializations
* the Authorization module which can consume `Quad`s from the `StoreManager` to make access decisions

This also means that if a resource is stored and later retrieved, but no translations were necessary (e.g. PUT turtle then GET turtle), then the representation does not get parsed and does not pass through the `StoreManager`. Instead, both on write and on read, it follows the same path as LDP-NR resources. This means we have two main code paths for data passing through the server: direct, and through the StoreManager. We could have chosen to always translate in both directions, and have only one path for RDF data, and we did experiment with that because it sounds very attractive as a simplification. However, LDP-NR resources will still have to follow the other path. Also, comments and choice of prefix name in Turtle docs would be stripped, and RDFa docs would probably require yet a third path where somehow the RDF travels differently than the HTML? All gets a bit too messy.

I can easily add an option, ALWAYS_PARSE_RDF, if there is a request for that from developers who depend on this module and wish to use it that way (for instance, because they only want to store syntactically valid RDF), and I'll do so if such a request arrives.

So to summarize, we have quite a simple architecture:
* http message comes in, get parsed lazily into an object with methods like `getWebId()`, so that there is a representation of the request containing access to all the info the operation handler might need, but without doing unnecessary work on parsing parts of the http message that the handler is not going to need (thanks to Ruben for proposing this approach!)
* An array of operation handlers then all get a chance, in turn, to say if they can handle the request. The first handler that says yes gets chosen. Thanks to Ruben again for proposing this middle-ware style approach; the different operations that we're implementing all have quite a few quirks, and so it's very clean that we now encapsulate each operation separately from the others.

A note about Factories: https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-1-0.pdf uses a Factory pattern which I generally don't like that much, and especially here I think it's overkill; the array of operation handlers is very easy to reason about and when you see it in the code, you immediately understand what that code does. In my experience, Factories usually end up being more abstract than that without really adding any maintainability.

Once an operation handler has been picked, the Authorization module decides if the required access modes of the operation are met by the granted access modes of the credentials that have first been verified by the Authentication module.

There is a special case for append-only operations, which is a little bit annoying, but the spec requires it.

If access check is OK, the chosen operation handler executes the request and produces the response. In doing so, it may access the persistence layer through its BufferTree interface, and access the StoreManager for any translations and other RDF-aware operations it might have to do.

So after this long intro, coming back to the topic of this issue, representations occur in two ways: RDF-aware, and direct. In the direct path, the representations are not "understood" as representing anything, it's just streaming as-is from network to persistence or from persistence to network. So this part of the architecture is not representation-oriented.

Representations are also parsed into the StoreManager and there we do use a Representation class, which is called ResourceData. It contains basically content-type, e-tag, and body that together form the representation, and it's what the StoreManager consumes when parsing a resource into the store from a representation. These can basically come from three different places: from an incoming http message, from a ResourceNode that is read from the persistence module (obtained using `BufferTree#getResourceNode`), or from an external resource, retrieved over http, such as a remote group or profile that's references in an ACL doc.

**Comment by michielbdejong** [comment]
related to the topic of representation-oriented architecture, I'm also trying to understand the ResourceStore from page 4 of https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-1-0.pdf
It feels like it would cover both the StoreManager and the BufferTree in a single class, so probably. It seems that what the wac-ldp module would need would be a composite store that combines a TripleStore around the StoreManager, and a FileSystemStore/RedisStore/etc for the BufferTree part, but then splitting on content-type rather than on UrlPattern, to decide if something is an LDP-RS or an LDP-NR.

I don't see how that abstraction would make life easier for an operation-handler, i think the handler knows at any point whether it wants to talk to the StoreManager or to the BufferTree. Putting those two together in a superclass feels like it would trigger more confusion than it would solve, so I think i'll keep things as they are.

**Comment by acoburn** [comment]
It is worth noting that Trellis does not use the representation-oriented design. Instead, any representation is converted into/out of RDF (in the case of LDP-RS) immediately, in the HTTP layer. That way, the `ResourceService` works only with RDF abstractions (e.g. `Triple` objects). For LDP-NR resources, they follow a different path, based on Link header values and they are streamed directly into/out of the binary storage back-end.

There are advantages and disadvantages of these two designs. An advantage of the Trellis design is that it is possible to partition the RDF into separate underlying stores: membership triples are pulled from one place, containment triples from somewhere else, regular statements from yet another location. This is useful for high scalability, highly parallelizable environments and also for the case where Direct and/or Indirect Containment is to be supported.

The downside to the Trellis architecture is that append-only PATCH is more expensive: the resource must first be read entirely into memory, the patch is applied and then the entire graph is stored to the persistence layer. For a large resource where a single triple is to be added, this is less efficient.

Another downside to Trellis is that the serialization (i.e. form) of the RDF document will not be preserved: Trellis does not store RDF resources as Turtle documents. For instance, if there is a particular order of the triples or in-line comments in a Turtle document, those are not preserved. In a representation-oriented design, that document form can be preserved.

Finally, the representation-oriented architecture makes it possible to stream an RDF resource directly from the persistence layer if the storage format matches the requested format (e.g. stored as Turtle and requested as Turtle). This saves on any parsing/serialization overhead.

There are other advantages of the Trellis design that I'm not going into here, but the point I'm trying to make is that all of these designs have trade-offs. The important thing it to have a clearly articulated design so that it is easy to discuss these high-level design choices. From my perspective, having a clear separation between API (interfaces) and implementation code will give us the ability to have those high-level conversations without needing to be so close to the details of the implementation.
