### ISSUE TITLE
Rename RDF component to ResourceStore

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#78]
I realized that both @RubenVerborgh and @pmcb55 cling very much to the idea of having a layer ("ResourceStore") that is effectively almost equal to the storage, but with two differences: it represents containers as resources, and it knows how to convert between RDF representations.

So if we rename the central box in https://github.com/inrupt/wac-ldp/blob/cac43109d10510eab4339a630661f660dccd12f3/README.md#wac-ldp from RDF to ResourceStore, and then remove the arrow from ExecuteTask to BlobTree (just make it go "through" the ResourceStore component), I think we would probably understand each other a lot better. :)

**Comment by RubenVerborgh** [comment]
> it knows how to convert between RDF representations

Some nuance here (and pointing to https://github.com/RubenVerborgh/solid-server-architecture/issues/4#issuecomment-490811159).

There are arguments either way:
1. The serialization of responses should be done by a dedicated serializer instead, since this is knowledge that is independent of specific stores (file-based, triplestores, …).
2. A resource store can have direct access to multiple representations, and hence should do conversions (for instance, there might be multiple representations on disk).

I'm inclined to say that both arguments are valid, and can hold at the same time. For instance, a store could do _limited_ conneg between some formats it can easily support, but more advanced conversions are done by filters.

Here, we also have two possibilities. Either full conneg could be implemented in a `ResponseGenerator`, or we could implement the Decorator pattern to create a dedicated `ResourceStore` implementation for conversions. I will sketch this second solution below.

| TranscodingStore implements ResourceStore |
|:------------------------------------------|
| - ResourceStore internalStore               |
| - Array&lt;FormatTranscoder&gt; transcoders |

| &lt;&lt;interface&gt;&gt; FormatTranscoder  |
|:--------------------------------------------|
| + supports(in : ContentType, out : RepresentationPreferences) : Promise<ContentType?> |
| + transcode(Representation, RepresentationPreferences) : Promise<Representation>      |

So `TranscodingStore` is a `ResourceStore` implementation that does not store anything itself, but rather relies on an `internalStore` that does. It forwards all methods to `internalStore`, but will then take `Representation` responses through all of its `FormatTranscoder`s to try to satisfy the agent's representation preferences.

Note that this solution does satisfy argument 1 above (as well as 2), and that transcoding knowledge remains local.

**Comment by michielbdejong** [comment]
Indeed, we keep the BlobTree as `internalStore`, and the RDF/ResourceStore component becomes a TranscodingStore that relies on it (and on a http client so that it can also transcode remote resources)

**Comment by kjetilk** [comment]
I think it would make it easier to discuss this if ResourceStore could be thought of as a composition [in traits-based programming](http://scg.unibe.ch/research/traits). I primarily think of it in terms of enabling query interfaces and in terms of [our paper on pushing complexity down the stack](http://ceur-ws.org/Vol-1268/paper14.pdf), but I also think it would make the conneg case above much more intuitive: A store that can do conneg will implement a conneg trait, or perhaps rather a serialization trait. It would then not be a part of the core ResourceStore trait, but a separate trait that is composed to a class when needed. 

Then, you'd have traits for managing etags and mtimes, computing the statistics needed for clients and proxies to do federated query optimizations, etc.

I think @RubenVerborgh 's proposed ResourceStore API with methods for `getRepresentation`, `addResource`, `setRepresentation`, `deleteResource` and `modifyResource` is a good trait to begin with, but the full API would be composed with a number of other traits that can aid other functionalities. Some of the ResourceStore functionality could mirror what we've done for quadstores in [Attean](https://metacpan.org/release/Attean), part of which is described in the above paper, but where we can compose stores starting with the `QuadStore` trait, then there's mutable traits, etag traits, mtime traits, and those things can be wrapper by a Model, which guarantees concistency, but also adds support for cost models, bulk updates, transactions (experimental for now), etc.

**Comment by michielbdejong** [comment]
Got this as RdfFetcher now. Moved readAcl into it, so that function moves from the ACL module to the RDF module, which makes sense if you think about it (it's just reading RDF, not interpreting its meaning). Will do a separate issue for module/method naming and alignment between code and docs.
