### ISSUE TITLE
update diagram

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#89]
![wac-ldp components (4)](https://user-images.githubusercontent.com/408412/60094955-712a0080-971b-11e9-8756-74448f93e92e.png)

**Comment by michielbdejong** [comment]
![wac-ldp components (5)](https://user-images.githubusercontent.com/408412/60095471-a08d3d00-971c-11e9-80c5-a4745f5c6271.png)

**Comment by michielbdejong** [comment]
![wac-ldp components (6)](https://user-images.githubusercontent.com/408412/60110655-734f8780-973a-11e9-86c7-089968d3d8e2.png)

**Comment by michielbdejong** [comment]
![wac-ldp components (7)](https://user-images.githubusercontent.com/408412/60207345-a4f04d80-9823-11e9-9ea5-831d83e1a314.png)

**Comment by michielbdejong** [comment]
![WacLdp Architecture (1)](https://user-images.githubusercontent.com/408412/60423870-6675dc80-9bef-11e9-8b98-4b22506d9cb0.png)

**Comment by RubenVerborgh** [comment]
Legend:
- WacLdp is [WacLdp Architecture of 28 June 2019](https://github.com/inrupt/wac-ldp/issues/89#issuecomment-507179588)
- SA is [Solid Architecture v1.0.0](https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-0-0.pdf)

### RdfLayer
- In WacLdp, `getRepresentation` takes a `format` parameter.
  However, the intention of SA with `RepresentationPreferences` is to encapsulate a longer list of preferences,
  including `Content-Type` but also `Content-Language`, JSON-LD frames, profiles, Memento date-time, etc.
  Crucially, `format` cannot be a single format, but rather a list of preferences.
  ("I like RDF/XML, but if not available, JSON-LD is acceptable. No Turtle though.")
  
- I am confused by `getRepresentation` taking a `SparqlQuery` parameter. This would require whatever is invoking it to have RDF/SPARQL knowledge, but this is not the case. I think this can simply be removed for now; query interfaces will be separate anyway.

- `ResourceData`: the `Representation` interface in SA has not been detailed yet in the diagram, but it is more than just data. Will be able to explain this better with additional drawings; for now I just want to point out SA's adherence to the REST terminology of resource and representation.

### WacLdpTask
- Would probably be good to draw this out in detail.

- Not strongly opposed, but there seems to be a risk of [violating the Law of Demeter](http://misko.hevery.com/2008/07/18/breaking-the-law-of-demeter-is-like-looking-for-a-needle-in-the-haystack/) (very good piece, as are all of Hevery's articles). In another architecture diagram, I have seen details of `WacLdpTask` that seemed to contain a lot of different properties. The risk is that, over time, they would be used to spread too much knowledge across different components. I have seen that happen in NSS, where the `Request` object became the god object that all components would read and write to. The main reason why I proposed TypeScript for vNext, was to _enforce_ that classes could not read more than what they needed to know.

### WacLdpResponse
- I wonder to what extent the response needs to be specific to WacLdp; maybe we can have a more generic response class (not that urgent/important now).

### Router
- Unclear what the delta is with `HttpServer`, since `Router` only has one method and it has a one-to-one relationship with `HttpServer`.
  For what it's worth, SA's `HttpServer` would basically do a loop over all of its `HttpHandler`s until it finds a matching one, and then simply delegate to it. So not a lot of logic.
  
### GlobHandler
- I strongly suggest to get this out of LDP. It is not LDP logic at all.
  It is a custom Solid extention to the HTTP interface, but _not_ to the LDP interface. LDP is for individual resources.
  
- Furthermore, globbing provides a DOS attack vector, will never make the v1.0 spec because of that, is only wanted by one person, and has a zero-overhead client-side abstraction. It's basically a flaw that ended up in the non-authoritative v0.7 draft spec, and we don't want it.

### OperationHandler
- `Array<Mode>` can probably function better as a class such as [`PermissionSet`](https://github.com/RubenVerborgh/solid-server-ts/blob/a93717ec02389ba10c79975fc2bbdbe8d18336f0/src/permissions/PermissionSet.ts), which can contain logic for subsetting, deals with `Append`, is non-modifiable, etc.

**Comment by michielbdejong** [comment]
> I am confused by getRepresentation taking a SparqlQuery parameter. This would require whatever is invoking it to have RDF/SPARQL knowledge, but this is not the case. I think this can simply be removed for now; query interfaces will be separate anyway.

This is for https://github.com/solid/solid-spec/blob/master/api-rest.md#alternative-using-sparql

> we don't want globbing

that's a spec issue, not a pod-server architecture issue

**Comment by RubenVerborgh** [comment]
Well, yes and no. The spec and its evolution have architectural consequences.

Both the per-resource SPARQL query interface and globbing are features that we know with 100% certainty will _not_ end up in the Solid specification. They are currently only listed in the draft documents.

Therefore, it would be very unwise to adjust the architecture, even in the slightest way, to accommodate for these features.

Furthermore, even _if_ some variant of these features will be included, LDP is the wrong place for this. LDP should only do LDP features, and SPARQL and globbing are not part of those.

Hence, I want to underscore that the goal of vNext is to support Solid in the future, and the goal of WacLdp specifically to support WAC and LDP. Goals that are not part of either, should not have a place in the architecture. They might be implemented as temporary code on the side (although I emphasize that they are _not_ requested by anyone currently in the project, and thus are not worth spending valuable time on).

**Comment by michielbdejong** [comment]
See your point about having a 'wac-ldp' module that does not implement any Solid-specific things, but then it gets quite ugly if we need to slap them on separately at the https://github.com/inrupt/pod-server level. For instance, if the implementation of the `WAC-Allow` header is at the pod-server level, then that requires a lot of ugly back-and-forth between pod-server and wac-ldp. Let's defer this decision to @acoburn.

**Comment by RubenVerborgh** [comment]
Thanks for raising that; `WAC-Allow` is a very interesting case; we want to keep an eye on that. It indeed violates some of the assumptions, notably the interface to the ACL component.

**Comment by acoburn** [comment]
Trellis does not currently support `WAC-Allow`, but given how JAX-RS works in Java-land, adding this feature would be simple to implement while retaining modularity between the LDP/Solid component and the WAC component (the WAC module would implement a [ContainerResponseFilter](https://docs.oracle.com/javaee/7/api/javax/ws/rs/container/ContainerResponseFilter.html) to add the appropriate header values to the HTTP response). Articulating this in the UML diagrams in a platform-agnostic way will be the challenge.

**Comment by RubenVerborgh** [comment]
>     * Will be able to explain this better with additional drawings

Done in https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-1-0.pdf
